[metadata]
creation_date = "2020/10/14"
ecs_version = ["1.6.0"]
maturity = "production"
updated_date = "2020/10/14"

[rule]
author = ["Elastic"]
description = """
Identifies use of SSH Plink utility to establish RDP over a reverse SSH Tunnel. This could be indicative of adversary lateral
movement to interactively access restricted networks.
"""
from = "now-9m"
index = ["logs-endpoint.events.*", "winlogbeat-*"]
language = "eql"
license = "Elastic License"
name = "Remote Desktop Tunneling using SSH Plink Utility"
references = ["https://blog.netspi.com/how-to-access-rdp-over-a-reverse-ssh-tunnel/"]
risk_score = 73
rule_id = "76fd43b7-3480-4dd9-8ad7-8bd36bfad92f"
severity = "high"
tags = ["Elastic", "Host", "Windows", "Threat Detection", "Lateral Movement"]
type = "eql"

query = '''
process where event.type in ("start", "process_started") and
  (process.name == "plink.exe" or process.pe.original_file_name=="Plink") and
    process.args=="*:3389" /* RDP port in commandline */
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1021"
name = "Remote Services"
reference = "https://attack.mitre.org/techniques/T1021/"


[rule.threat.tactic]
id = "TA0008"
name = "Lateral Movement"
reference = "https://attack.mitre.org/tactics/TA0008/"

